### ISSUE TITLE
Dependancy in 1.10 of Orchard.jQuery = broken

### ISSUE THREAD

**Issue by donaldboulton** [IDeliverable/IDeliverable.Widgets#17]
Dependancy in 1.10 Orchard.jQuery
Which does not exist anymore. Tried to change it in Module.txt to Orchard.Resources still cannot get it to work.
Your module works really great up to 1.9.2 cannot get it to work with 1.9.3 or 1.10.
Could not get most non core modules to work, "various errors", in 1.9.3 some I get working in 1.10

**Comment by sfmskywalker** [comment]
That's interesting, because Orchard.jQuery should  still exist in 1.9.3. However, it is marked as deprecated. Did you clone the source or download a package? If so, which one? In any case, we'll make sure to update our modules. Thanks for letting us know.

**Comment by donaldboulton** [comment]
Added Orchard jQuary and widget EX now shows up in Content Parts but does not automatically attach to Widget content types and if you try to add it to a widget there is no listing of it to "Add Parts To", a widget. Caching does not work and Widget Container does not show up. Tried uninstalling and using the development code branch and got = The assembly reference 'System.Data.DataSetExtensions' could not be loaded for module 'IDeliverable.Widgets'.  Removed form project file   `<Reference Include="System.Data.DataSetExtensions" />` and still not showing up as types or parts but now in Modules features. Enable all 3 and still nothing works. Widget EX checkbox for attachable was not checked, checked it now it does list in "Add Parts To", a widget, so I added to several that worked before = Still do not see any cache files on widgets, No widget containers....

**Comment by donaldboulton** [comment]
Debug log in 1.10.
2016-02-19 16:12:29,954 [11] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/IDeliverable.Widgets/IDeliverable.Widgets.csproj.
System.Web.HttpCompileException (0x80004005): e:\web\mansbook\donboulton2\Modules\IDeliverable.Widgets\Filters\WidgetOutputCacheFilter.cs(194): error CS1501: No overload for method 'ToString' takes 1 arguments
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath) in z:\TeamCityAgent\work\9f6cd39ff0f68f41\src\Orchard\Environment\IBuildManager.cs:line 53

**Comment by donaldboulton** [comment]
Fixed in web config
 a removed assembly because of VS 2015 build errors
 `<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
Add       
`<add assembly="System.Web.Enity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`

` <add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
       
Fixed Errors full null propagating operator is not available in C# 5. Please use language version 6 or greater.
for `(CultureInfo.InvariantCulture))`in WidgetOutputCacheFilter.cs

VS 2015 4.5.1 or greater error fixed it by installing

Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

Works in 1.10 now
